bump version with date (for xcp 57600 baud rate access grant)
inventables/grbl-xcp pull request #11
Opened 2022-03-14 20:15 UTC by hphu3

^^^

2022-03-15 22:15 UTC, rodovich reviewed
For the sake of testing at 57600 baud, I think we also would need to build with a different value of

https://github.com/inventables/grbl-xcp/blob/564ecb2638e652a15de49f982a186d9cf1c44aef/grbl/config.h#L42

2022-03-15 22:30 UTC, hphu3 commented
> For the sake of testing at 57600 baud, I think we also would need to build with a different value of
> 
> https://github.com/inventables/grbl-xcp/blob/564ecb2638e652a15de49f982a186d9cf1c44aef/grbl/config.h#L42

I thought easel was responsible for the baud rate number (Since it has the controller cycling between different rates)

2022-03-15 23:19 UTC, neilpa-inv requested changes

2022-03-15 23:19 UTC, neilpa-inv commented on grbl/grbl.h
> +#define GRBL_VERSION "1.1h-XCP-20220314"
The next `#define` already sets the date. If we're globally including it now then it should be removed. However, lets keep the same format as was previously used [here](https://github.com/inventables/grbl-xcp/blob/564ecb2638e652a15de49f982a186d9cf1c44aef/grbl/report.c#L371) (which also needs to be tweaked).

2022-03-15 23:19 UTC, neilpa-inv commented on grbl/grbl.h
> +#define GRBL_VERSION "1.1h-XCP-20220314"
Can you also update the [comment here](https://github.com/inventables/grbl-xcp/blob/master/bootloader/combine.sh#L22)

2022-03-16 17:51 UTC, neilpa-inv approved these changes

2022-03-16 19:48 UTC, merged